version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
        interval: daily
    - package-ecosystem: cargo
      directory: /
      schedule:
        interval: weekly
    - package-ecosystem: cargo
      directory: /crates/file_bundle_cli
      schedule:
        interval: daily